<?php
/* Messaging module installer: creates tables owned by messaging/email features. */
if (!defined('PRFX')) {
    exit;
}

$sqls = array(
    "CREATE TABLE IF NOT EXISTS `" . PRFX . "TABLE_BUSINESS` (
        `BUSINESS_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `BUSINESS_NAME` VARCHAR(255) DEFAULT NULL,
        `BUSINESS_ADDRESS` VARCHAR(1000) DEFAULT NULL,
        `BUSINESS_PHONE` VARCHAR(100) DEFAULT NULL,
        `CONTRACT_RENEWAL_DATE` DATE DEFAULT NULL,
        `PRODUCT_PREFERENCES` TEXT,
        `DATA` TEXT,
        `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
        KEY `BUSINESS_NAME` (`BUSINESS_NAME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS `" . PRFX . "TABLE_CONTACT` (
        `CONTACT_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `BUSINESS_ID` INT DEFAULT NULL,
        `FIRST_NAME` VARCHAR(255) DEFAULT NULL,
        `LAST_NAME` VARCHAR(255) DEFAULT NULL,
        `EMAIL` VARCHAR(255) DEFAULT NULL,
        `PHONE` VARCHAR(100) DEFAULT NULL,
        `JOB_TITLE` VARCHAR(255) DEFAULT NULL,
        `SOCIAL_HANDLE` VARCHAR(255) DEFAULT NULL,
        `NOTES` TEXT,
        `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
        KEY `BUSINESS_ID` (`BUSINESS_ID`),
        KEY `EMAIL` (`EMAIL`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS `" . PRFX . "EMAIL_ACCOUNTS` (
        `ACCOUNT_ID` INT AUTO_INCREMENT PRIMARY KEY,
        `PROVIDER` VARCHAR(32) NOT NULL,
        `EMAIL` VARCHAR(255) NOT NULL,
        `ACCESS_TOKEN` TEXT,
        `REFRESH_TOKEN` TEXT,
        `EXPIRES_AT` BIGINT DEFAULT 0,
        `SCOPES` TEXT,
        `EMPLOYEE_ID` INT DEFAULT NULL,
        `ENABLED` TINYINT(1) DEFAULT 1,
        `LAST_SYNC` BIGINT DEFAULT NULL,
        `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8",
    "CREATE TABLE IF NOT EXISTS `" . PRFX . "EMAIL_LOG` (
        `LOG_ID` INT AUTO_INCREMENT PRIMARY KEY,
        `ACCOUNT_ID` INT DEFAULT NULL,
        `MESSAGE_ID` VARCHAR(255),
        `THREAD_ID` VARCHAR(255),
        `DIRECTION` VARCHAR(10) DEFAULT 'in',
        `FROM_EMAIL` VARCHAR(255),
        `TO_EMAIL` TEXT,
        `CC_EMAIL` TEXT,
        `BCC_EMAIL` TEXT,
        `SUBJECT` VARCHAR(512),
        `BODY` LONGTEXT,
        `RAW` LONGTEXT,
        `LINKED_CUSTOMER_ID` INT DEFAULT NULL,
        `LINKED_LEAD_ID` INT DEFAULT NULL,
        `LINKED_EMPLOYEE_ID` INT DEFAULT NULL,
        `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8",
    "CREATE TABLE IF NOT EXISTS `" . PRFX . "EMAIL_TRACKING` (
        `TRACK_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `ACCOUNT_ID` INT NOT NULL DEFAULT 0,
        `EMAIL_ID` VARCHAR(100) NOT NULL DEFAULT '',
        `RECIPIENT` VARCHAR(255) NOT NULL DEFAULT '',
        `EVENT` VARCHAR(20) NOT NULL DEFAULT '',
        `LINK` VARCHAR(2000) NOT NULL DEFAULT '',
        `IP` VARCHAR(45) NOT NULL DEFAULT '',
        `USER_AGENT` VARCHAR(1024) NOT NULL DEFAULT '',
        `REFERRER` VARCHAR(2000) NOT NULL DEFAULT '',
        `META` TEXT,
        `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        KEY `EMAIL_ID` (`EMAIL_ID`),
        KEY `RECIPIENT` (`RECIPIENT`),
        KEY `EVENT` (`EVENT`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS `" . PRFX . "NOTIFICATIONS` (
        `NOTIFICATION_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `EMPLOYEE_ID` INT DEFAULT NULL,
        `TRACK_ID` INT DEFAULT NULL,
        `EMAIL` VARCHAR(255) DEFAULT NULL,
        `EVENT` VARCHAR(50) DEFAULT NULL,
        `LINK` VARCHAR(2000) DEFAULT NULL,
        `DATA` TEXT,
        `IS_READ` TINYINT(1) NOT NULL DEFAULT 0,
        `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        KEY `EMPLOYEE_ID` (`EMPLOYEE_ID`),
        KEY `IS_READ` (`IS_READ`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
);

$errors = array();
foreach ($sqls as $sql) {
    if (!$db->Execute($sql)) {
        $errors[] = $db->ErrorMsg();
    }
}

if ($errors) {
    throw new RuntimeException("Messaging install errors:\n" . implode("\n", $errors));
}

echo 'Messaging module tables created successfully.';
