-- Create tables for mailbox connectors and email logging
-- Replace __PREFIX__ with your table prefix (or remove if none)

CREATE TABLE IF NOT EXISTS __PREFIX__EMAIL_ACCOUNTS (
  ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
  PROVIDER VARCHAR(32) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  ACCESS_TOKEN TEXT,
  REFRESH_TOKEN TEXT,
  EXPIRES_AT BIGINT DEFAULT 0,
  SCOPES TEXT,
  EMPLOYEE_ID INT DEFAULT NULL,
  ENABLED TINYINT(1) DEFAULT 1,
  LAST_SYNC BIGINT DEFAULT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS __PREFIX__EMAIL_LOG (
  LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_ID INT DEFAULT NULL,
  MESSAGE_ID VARCHAR(255),
  THREAD_ID VARCHAR(255),
  DIRECTION VARCHAR(10) DEFAULT 'in',
  FROM_EMAIL VARCHAR(255),
  TO_EMAIL TEXT,
  CC_EMAIL TEXT,
  BCC_EMAIL TEXT,
  SUBJECT VARCHAR(512),
  BODY LONGTEXT,
  RAW LONGTEXT,
  LINKED_CUSTOMER_ID INT DEFAULT NULL,
  LINKED_LEAD_ID INT DEFAULT NULL,
  LINKED_EMPLOYEE_ID INT DEFAULT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
