-- Create table to store external OAuth identities linked to employees
-- Replace __PREFIX__ with your table prefix

CREATE TABLE IF NOT EXISTS __PREFIX__OAUTH_IDENTITIES (
  IDENTITY_ID INT AUTO_INCREMENT PRIMARY KEY,
  PROVIDER VARCHAR(32) NOT NULL,
  EXTERNAL_ID VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  ACCESS_TOKEN TEXT,
  REFRESH_TOKEN TEXT,
  EXPIRES_AT BIGINT DEFAULT 0,
  SCOPES TEXT,
  EMPLOYEE_ID INT DEFAULT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY provider_external (PROVIDER, EXTERNAL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
