<?php
/* Tasks module installer. */
if (!defined('PRFX')) {
    exit;
}

$sql = "CREATE TABLE IF NOT EXISTS `" . PRFX . "TASKS` (
    TASK_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRIORITY VARCHAR(20) NOT NULL DEFAULT 'Normal',
    DUE_DATE DATE DEFAULT NULL,
    ASSIGNED_TO INT DEFAULT NULL,
    IS_COMPLETE TINYINT(1) NOT NULL DEFAULT 0,
    CREATED_BY INT DEFAULT NULL,
    COMPLETED_BY INT DEFAULT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NULL DEFAULT NULL,
    COMPLETED_AT TIMESTAMP NULL DEFAULT NULL,
    INDEX IDX_TASKS_ASSIGNED_TO (ASSIGNED_TO),
    INDEX IDX_TASKS_DUE_DATE (DUE_DATE),
    INDEX IDX_TASKS_COMPLETE (IS_COMPLETE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";

if (!$db->Execute($sql)) {
    throw new RuntimeException(
        'Could not create the tasks table: ' . $db->ErrorMsg()
    );
}

echo 'Tasks table created successfully.';
