-- Create contacts and business tables for messaging contacts management
-- Replace `PREFIX_` with your configured PRFX when running

CREATE TABLE IF NOT EXISTS `PREFIX_TABLE_BUSINESS` (
  `BUSINESS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BUSINESS_NAME` varchar(255) DEFAULT NULL,
  `BUSINESS_ADDRESS` varchar(1000) DEFAULT NULL,
  `BUSINESS_PHONE` varchar(100) DEFAULT NULL,
  `CONTRACT_RENEWAL_DATE` date DEFAULT NULL,
  `PRODUCT_PREFERENCES` text,
  `DATA` text,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`BUSINESS_ID`),
  KEY `BUSINESS_NAME` (`BUSINESS_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PREFIX_TABLE_CONTACT` (
  `CONTACT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BUSINESS_ID` int(11) DEFAULT NULL,
  `FIRST_NAME` varchar(255) DEFAULT NULL,
  `LAST_NAME` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `PHONE` varchar(100) DEFAULT NULL,
  `JOB_TITLE` varchar(255) DEFAULT NULL,
  `SOCIAL_HANDLE` varchar(255) DEFAULT NULL,
  `NOTES` text,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CONTACT_ID`),
  KEY `BUSINESS_ID` (`BUSINESS_ID`),
  KEY `EMAIL` (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
