-- Create notifications table for reps
-- Replace `PREFIX_` with your configured PRFX

CREATE TABLE IF NOT EXISTS `PREFIX_NOTIFICATIONS` (
  `NOTIFICATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) DEFAULT NULL,
  `TRACK_ID` int(11) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `EVENT` varchar(50) DEFAULT NULL,
  `LINK` varchar(2000) DEFAULT NULL,
  `DATA` text,
  `IS_READ` tinyint(1) NOT NULL DEFAULT 0,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`NOTIFICATION_ID`),
  KEY `EMPLOYEE_ID` (`EMPLOYEE_ID`),
  KEY `IS_READ` (`IS_READ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
